services:
  bot:
    build: .
    image: ghcr.io/quantummechanicsenjoyer/kurisumakise-bot:latest
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - .:/app
    command: cargo run --release
